baseURL = "https://alexbozhenko.github.io/"
title = "Alex Bozhenko"
languageCode = "en-us"
theme = "terminal"

# Pagination (new format)
[pagination]
pagerSize = 10

# Enable safe HTML in Markdown
[markup.goldmark.renderer]
  unsafe = true

[params]
  # Basic configuration
  contentTypeName = "posts"
  showMenuItems = 2
  fullWidthTheme = false
  centerTheme = true
  #Toc = true
  
  # Author information
  author = "Alex Bozhenko"
  
  # Theme appearance
  themeColor = "blue"
  
  # Features configuration
  showLanguageSelector = false
  enableGitInfo = true
  autoCover = true  # Uses cover.(jpg|png|webp) from resource dir automatically
  showLastUpdated = true  # Shows last updated date on posts
  
  # Reading experience
  readingTime = true  # Show reading time estimates
  
  # Comments configuration
  [params.utterances]
    repo = "alexbozhenko/alexbozhenko.github.io"
    issueTerm = "title"
    theme = "github-dark"
    label = "Comments"

# Language specific configurations
[languages]
  [languages.en]
    title = "Alex Bozhenko"
    subtitle = "Computer enthusiast"
    owner = "Alex Bozhenko"
    keywords = "programming,software development,golang"
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    missingContentMessage = "Page not found..."
    missingBackButtonLabel = "Back to home page"

    [languages.en.params.logo]
      logoText = "cd ~/alex"
      logoHomeLink = "/"

    # Main menu
    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/posts"
